### ISSUE TITLE
演示后台采用 `demo` 帐号密码登录失败

### ISSUE THREAD

**Issue by puzzle9** [Mereithhh/van-blog#1]
![image](https://user-images.githubusercontent.com/13518196/185573504-4eeff3c5-bd70-40a4-88f2-72196be98419.png)

**Comment by Mereithhh** [comment]
感谢反馈！有人把后台密码改了 （我也是没想到……）。刚刚加了演示站锁定后台密码的功能，之后不会出现这种情况了。

![image](https://user-images.githubusercontent.com/22872368/185667576-9867b9d0-6131-4d8f-9164-15765cb55779.png)
