### ISSUE TITLE
评论区登录bug与优化体验

### ISSUE THREAD

**Issue by darkchoco10099** [Mereithhh/van-blog#10]
## 首先非常非常感谢作者开发的个人博客项目，真的解决了我几个月以来找一个好的自搭博客的刚需！通过初步体验目前有如下两个小问题：
- 评论区点击登录会显示404报错，不登录的话评论就是匿名
- 打开文档右侧向下滑块过小不易操作，右侧目录块滑块同样痛点
## 希望这个项目越来越牛逼，star数越来越多，真的非常非常使用易用美观！

**Comment by Mereithhh** [comment]
感谢反馈，这两个问题我会在今天着手解决。有最新消息会反馈给你。

**Comment by Mereithhh** [comment]
那两个滑块过小的问题可以截个图吗？

**Comment by darkchoco10099** [comment]
![image](https://user-images.githubusercontent.com/50414028/187605540-f516d2fc-447e-4701-acb1-68d392c7859f.png)
这两个滑块也不能算问题，就是感觉有点小，不太好滑动，如果为了符合整体美感协调设计的话，那这样确实挺美观的

**Comment by Mereithhh** [comment]
感谢反馈。我考虑一下酌情增加一下滑块宽度，或者可能会在后台增加一个配置项。

**Comment by darkchoco10099** [comment]
非常感谢作者！

**Comment by Mereithhh** [comment]
刚才发布的 `v0.26.0` 已经修复了评论登录问题，滑块的宽度也酌情增加了。您可以升级看一下，如果新版的宽度还是觉得窄一点，您可以联系我，我将考虑加一个配置项。

这个 issue 我先关了，有问题您再提出来。

感谢反馈！
