### ISSUE TITLE
导出希望支持图片一起打包导出

### ISSUE THREAD

**Issue by CryFeiFei** [Mereithhh/van-blog#11]

**Comment by Mereithhh** [comment]
可以描述一下您的使用场景吗？一起打包导出指的是本地图床，还是 oss 图床，还是都想要支持？

**Comment by CryFeiFei** [comment]
来信收到，我会尽快回复您

**Comment by Mereithhh** [comment]
打包是想在后台点一下按钮，直接下载一个压缩包吗？

**Comment by Mereithhh** [comment]
已经加上了， `v0.26.1` 已支持批量导出本地突出所有图片。在后台的`系统设置/图床设置` 中可以找到：

![image](https://user-images.githubusercontent.com/22872368/187729193-e53c28b8-0f71-4728-aee9-955e67a0f2f3.png)

**Comment by Mereithhh** [comment]
这个 issue 我先关了，如果您有其他需求场景，可以再发起 issue
