### ISSUE TITLE
目录渲染BUG，段落中的 # 号后的内容被渲染为一号标题

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#12]
段落中的 `#` 号后的内容被渲染为一号标题了，如图。

`#` 是被反引号包起来的

```
使用 `#` 号
```

![image](https://user-images.githubusercontent.com/14846416/187847248-b85963f4-3a20-4891-b4b2-bde113406de1.png)

**Comment by Mereithhh** [comment]
感谢反馈！我会尽快处理

**Comment by Mereithhh** [comment]
目录组件采用了 [markdown-navbar](https://www.npmjs.com/package/markdown-navbar) ，根据其文档，从设计上，目录组件只会解析二级标题及以下的级别，因为一级标题一般只会出现一次，从而不会解析一级标题：

> [Tips](https://www.npmjs.com/package/markdown-navbar#tips)

但解析了反引号中的 `#` 明显是错误的，暂时我将通过屏蔽反引号中的#号来修复这个问题。

至于一级标题的目录支持，可能需要魔改原有组件库或者自己实现一套更好的逻辑，我会加入排期中。

暂时而言可以用二级标题来替换一级标题。

**Comment by Mereithhh** [comment]
这个问题已经在 `v0.27.1` 中被修复了，issue 先关了，有问题再提。
