### ISSUE TITLE
编辑隐藏文章，文章内容不更新

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#13]
隐藏的文章，再次编辑后保存，前端查看依然还是更新前的内容。

**Comment by Mereithhh** [comment]
文章隐藏后，前台的列表和目录中都是不可见的呀。我测了一下，隐藏之后编辑保存，内容是更新了的，没有触发这个问题。

可以详细说明一下您的操作吗？在 `demo` 站点中吗？

**Comment by Mereithhh** [comment]
已经复现了，我修一下

**Comment by chenrizhi** [comment]
我看到你修复这个问题采取的方案是前台不允许查看隐藏文章，隐藏文章可以打开其实是有应用场景的。

比如我要写一个系列的文章，这一系列的文章如果都在主线显示，那么会显得很乱。我更倾向于将这一系列文章设为隐藏，然后将这些文章的URL地址汇总到一个新的文章里发布，这样会使得主线很整洁。

**Comment by Mereithhh** [comment]
您说的有道理，我会在下一个版本增加隐藏文章是否可以通过 `url` 打开的配置项。

**Comment by Mereithhh** [comment]
已经加了配置项了，默认不允许，打开配置项后可以通过 `URL` 访问被隐藏文章。（`v0.27.3`)

![image](https://user-images.githubusercontent.com/22872368/187890399-4ccc28d8-96ce-4445-9de6-41b17553aa3c.png)


这个 issue 就先关闭了。
