### ISSUE TITLE
代码块显示优化建议

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#14]
从我测试的结果来看，代码块是全部显示的，无论代码有多少行。

如果代码块有很多行，这样显示会占据文章页面中大量的页面空间，引起不好的阅读体验。

建议代码块只显示前30行，超过30行的内容折叠，通过点击“显示全部”的按钮来显示。

**Comment by Mereithhh** [comment]
感谢建议！

默认不折叠代码块是这样考虑的：对于阅读博客的人来说，阅读代码和阅读文章中的文字是没有区别的。对于会写大篇幅代码块当博客文章的人，以及会阅读此文章的人来说，代码块本身就是有价值的。

反而言之，觉得阅读大量代码块没有意义的话，也不会去写，也不会看。

比如您要写一个算法的实现，那文章的主体就是这个代码块了，折叠起来反而会影响体验。

我调研了主要的写作平台（github、知乎、掘金、CSDN等），他们的代码块都是不折叠的，我本人也觉得折叠起来很怪。

所以此条建议暂时不会被采纳，后期可能会加一条折叠代码块的配置项。
