### ISSUE TITLE
 Request mode is "same-origin" but the URL's origin is not same as the request origin

### ISSUE THREAD

**Issue by yuanshanhshan** [Mereithhh/van-blog#15]
Fetch API cannot load https://raymondblog-1308533672.cos.ap-shanghai.myqcloud.com/blog/img/favicon.jpg. Request mode is "same-origin" but the URL's origin is not same as the request origin https://www.huixinyixiao.work.

need help, thanks. 

头像地址是tencen 的cos

**Comment by Mereithhh** [comment]
您添加 `raymondblog-1308533672.cos.ap-shanghai.myqcloud.com` 到 `VAN_BLOG_ALLOW_DOMAINS` 了吗？

**Comment by yuanshanhshan** [comment]
加了，解决了，谢谢

**Comment by Mereithhh** [comment]
> 加了，解决了，谢谢

不客气

**Comment by yuanshanhshan** [comment]
我是做web3项目的，您这面有没有添加web3登录的想法呢？我一直想要实现的是通过metamask登录到自己的博客，然后进行相关的操作。

**Comment by Mereithhh** [comment]
后期我是有计划增加更多登录源支持的，添加 web3 登录是一个很好的想法，我会记录下来，有时间的话会尝试加一下。您有兴趣的话我很欢迎您提相关 pr。
