### ISSUE TITLE
希望可以增加一个从0搭建的教程，而不是docker这种

### ISSUE THREAD

**Issue by CryFeiFei** [Mereithhh/van-blog#16]
主流的博客平台都会有这个选项。希望增加

**Comment by Mereithhh** [comment]
感谢建议！

`VanBlog` 内部由很多微服务组成，直接部署到裸机环境可能会由于硬件、系统版本不同、软件不同而出现很多意料之外的问题，容器化可以提供很好的隔离环境，避免因这些差异导致的问题。

容器的话，基本上没什么学习成本，和一键部署也没区别了，迁移和升级都非常方便。

实际上，第一版方案是至少由 3 个微服务组成的分体式部署。后来才打包成了一个镜像。

`VanBlog` 的定位是简洁实用的，尽可能的减少复杂的配置。

裸机部署需要的`知识储备`的`可能遇到的坑`（不同的 node 版本、端口被占用、不同的系统、部署路径的影响等等）可能远大于简单的学习 `docker-compose up -d` 这一个指令。

我会采纳您的建议，出一个裸机部署的教程，但不会很详细到很小白向。因为我认为如果看不懂的话也没必要裸机部署了，裸机部署也不是很推荐。

（容器化真的是很好的技术，我很推荐大家都去学习一下）

**Comment by Mereithhh** [comment]
这个 issue 就先关了呀，感谢反馈！

**Comment by CryFeiFei** [comment]
来信收到，我会尽快回复您
