### ISSUE TITLE
两点建议或者说是疑问

### ISSUE THREAD

**Issue by praming** [Mereithhh/van-blog#17]
1.后续是否会出类似主题功能？不知道是否违背了VanBlog简洁的初衷，毕竟前端这个东西每个人的审美各有不同，还是希望自己来写。
2.是否能增加一个单页来放类似说说或者朋友圈这一类短语类？

**Comment by Mereithhh** [comment]
## 关于主题
  因为 VanBlog 想做到极致的快和简洁，所以使用了 `next.js` 和 `react.js`，导致页面渲染相关的代码运行时是固定的（或者说不固定的话会让页面变慢很多），这样导致传统意义上的主题功能不太好实现，起码我现在没想好怎么搞。

目前的想法是，将来会把前台渲染服务做成可插拔的。然后出一套生成前台渲染器的生成方案（输入相关的一些代码，可以生成一个符合 `vanblog` 要求的前台渲染器），这样也算是另类的主题实现了，到时候会有详细的文档。您有更好的方案也可以跟我说。

在排期上，自定义 css 将先上线，届时您可以先通过自定义 css 来装饰博客。或者您可以 fork 一下，改写现有的前台渲染器，然后和我联系，我将提前开发前台渲染服务可插拔功能。

## 自定义页面
其实现在就可以！您可以通过隐藏某篇文章，然后在后台开启通过 URL 访问被隐藏文章的功能。然后把这个 URL 添加到导航栏（在自定义导航栏设置中），或者到任何您想要的位置即可。这时候这篇文章其实就是自定义页面了。

在前台，您写在 markdown 里的 html 代码也会被正常渲染，所以完全可以当自定义页面来用。

完整的自定义页面功能在排期中，但比较靠后。

**Comment by Mereithhh** [comment]
这个 issue 就先关了哦
