### ISSUE TITLE
文章创建时间、本文链接问题

### ISSUE THREAD

**Issue by tlogin2021** [Mereithhh/van-blog#18]
1，旧博客文章迁移到 vanblog，不能自定义创建时间，时间线看上去一天就发布一大堆文章。应该提供自定义文章创建时间功能。

如果实现这个功能，个人认为“年月日时”已经足够，分和秒没必要。

2，点击目录的二级标题，刷新页面，此时版权声明里“本文链接”会自动添加二级标题文字。是否应该保持为永久链接？

**Comment by Mereithhh** [comment]
感谢反馈！

## 问题一
就现有功能来说，您可以通过文章管理的导入功能设置创建时间。[参考文档](https://vanblog.mereith.com/feature/basic/article.html#%E5%AF%BC%E5%85%A5-markdown)

非导入情况下自定义创建时间的功能，我会在下个版本加上，您可以关注一下！（可能今天晚上就发布了）

## 问题二
您的考虑有道理，这里出现二级标题文字不是特别合适。下个版我会修复这个问题。

**Comment by Mereithhh** [comment]
分和秒确实没有必要，实际上前端也不会展示那么详细的信息。 后端存储分和秒更多是为了排序等功能考虑的。 但为了个别用户的需求，我可能依然保留分和秒的输入框，但默认为0且可以不填。
