### ISSUE TITLE
隐藏文章会在上一篇/下一篇中显示

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#19]
文章设为隐藏，前台查看相邻的文章，在文章底部的上一篇/下一篇的位置会显示隐藏的文章，如图。

![image](https://user-images.githubusercontent.com/14846416/188036451-321d2835-0182-4a98-b71b-b888365328e9.png)

**Comment by Mereithhh** [comment]
感谢反馈，我修一下

**Comment by Mereithhh** [comment]
已修复 `v0.28.1`
