### ISSUE TITLE
问题反馈与建议

### ISSUE THREAD

**Issue by hxcaihm** [Mereithhh/van-blog#20]
1、因我想将这个博客作为我与小伙伴的知识库，所以希望可以多用户发表文章并区别文章是谁发表的。请问作者是否会考虑增加多用户的功能呢？
2、目前发现滚动到4~6级标题时，右侧目录所有的该级标题均会高亮显示。
![image](https://user-images.githubusercontent.com/66231422/188039691-4e14077c-ff72-4bc9-8cbe-f421b4809431.png)

**Comment by chenrizhi** [comment]
这个问题应该修过了，更新下版本看看。

**Comment by hxcaihm** [comment]
感谢回复！我目前的版本为最新版v0.28.0
![image](https://user-images.githubusercontent.com/66231422/188042124-ad56a22b-7ee5-4d31-b1a8-62bd7c4b2bc9.png)

**Comment by Mereithhh** [comment]
感谢反馈！
## 问题一
其实一开始我是没打算做多用户的，因为我没想到个人博客系统需要多用户的场景。但您说的确实比较合理，所以您觉得在文章中加一个可以设置作者的选项怎么样？

## 问题二
我去排查一下

**Comment by Mereithhh** [comment]
> 1、因我想将这个博客作为我与小伙伴的知识库，所以希望可以多用户发表文章并区别文章是谁发表的。请问作者是否会考虑增加多用户的功能呢？ 2、目前发现滚动到4~6级标题时，右侧目录所有的该级标题均会高亮显示。 ![image](https://user-images.githubusercontent.com/66231422/188039691-4e14077c-ff72-4bc9-8cbe-f421b4809431.png)

您可以提供一下出现问题的地址或者文章内容吗？

**Comment by hxcaihm** [comment]
> > 1、因我想将这个博客作为我与小伙伴的知识库，所以希望可以多用户发表文章并区别文章是谁发表的。请问作者是否会考虑增加多用户的功能呢？ 2、目前发现滚动到4~6级标题时，右侧目录所有的该级标题均会高亮显示。 ![image](https://user-images.githubusercontent.com/66231422/188039691-4e14077c-ff72-4bc9-8cbe-f421b4809431.png)
> 
> 您可以提供一下出现问题的地址或者文章内容吗？

```
# test1
## test2
### test3
#### test4
##### test5
###### test6

# test1
## test2
### test3
#### test4
##### test5
###### test6

# test1
## test2
### test3
#### test4
##### test5
###### test6
```
这个案例就可以复现该问题。

**Comment by hxcaihm** [comment]
> > 1、因我想将这个博客作为我与小伙伴的知识库，所以希望可以多用户发表文章并区别文章是谁发表的。请问作者是否会考虑增加多用户的功能呢？ 2、目前发现滚动到4~6级标题时，右侧目录所有的该级标题均会高亮显示。 ![image](https://user-images.githubusercontent.com/66231422/188039691-4e14077c-ff72-4bc9-8cbe-f421b4809431.png)
> 
> 您可以提供一下出现问题的地址或者文章内容吗？

```
# test1
## test2
#### test4
##### test5
###### test6

# test1
## test2
#### test4
##### test5
###### test6

# test1
## test2
#### test4
##### test5
###### test6
```
这个案例可以复现该问题，谢谢！

**Comment by Mereithhh** [comment]
## 问题原因
出现这个问题是因为多级子标题的名称一样导致的。 目录会通过名称来识别锚点
![image](https://user-images.githubusercontent.com/22872368/188043476-496533a5-f66e-493b-a31f-92d3ef9a33cb.png)

其实之前会自己生成一个没有语义的锚点可以避免这个问题（ #title-level-1 之类的），但我觉得不语义化，所以按名称来的。但是这样就要求每个标题必须独一无二了

**Comment by Mereithhh** [comment]
另外您觉得每篇文章可以单独设置作者的解决方案怎么样？

**Comment by hxcaihm** [comment]
> 

是的。我原文章标题不一样也会有这个问题。因文章比较长。难以在这里放下，如需文章我可邮箱发送给您。

**Comment by Mereithhh** [comment]
麻烦了！ 您可以发到这个邮箱：wanglu@mereith.com 。或者您在 demo 站导入/创建一篇文章也行。

**Comment by hxcaihm** [comment]
> 另外您觉得每篇文章可以单独设置作者的解决方案怎么样？

我觉得这是个不错的临时解决方案。
不过我的本意是其他小伙伴有权限登录我博客后台去发布文章，但是不希望他能修改我网站的设置（比如系统设置等博客站点关键信息的修改）。

**Comment by Mereithhh** [comment]
需求是合理的，我会把多用户和权限管理放到排期内，您可以关注一下，也许最近的版本更新就会上线。

**Comment by hxcaihm** [comment]
> 

已在demo站导入问题文章，谢谢！
https://blog-demo.mereith.com/post/101

**Comment by Mereithhh** [comment]
我试了一下，这个问题从现象上是因为从三级标题直接跳到了六级标题导致的。如果我把三级标题的下面改成四级标题就正常了。[修改后文章](https://blog-demo.mereith.com/post/101)

![image](https://user-images.githubusercontent.com/22872368/188045551-96cdce1b-5100-4230-bd0c-1f8f74e81997.png)

![image](https://user-images.githubusercontent.com/22872368/188046061-58012c82-170d-4c87-8a56-0167c717d199.png)


从代码上说应该是用的目录组件的判断问题，因为这个目录组件确实有些小问题，我已经计划进行重构目录组件了。  

但这个问题我认为是比较边缘的情况，完全可以通过正确的标题级别嵌套来规避，所以优先级不会太高。我会在手头的开发计划（多用户、自定义 css）都完成后再去处理这个问题。

**Comment by hxcaihm** [comment]
好的，非常感谢采纳我的建议！

**Comment by Mereithhh** [comment]
不客气！这个 issue 我就先关闭了，有其他问题您再提。
