### ISSUE TITLE
运行时间有问题

### ISSUE THREAD

**Issue by tfxidian** [Mereithhh/van-blog#21]
感谢大佬的付出，有一个小小的问题，我刚刚建站不到两个小时（可能也就一个小时），然而页面显示：本站居然运行了0天10小时30分54秒

![1662085948890](https://user-images.githubusercontent.com/19535272/188046153-b73ac861-46f8-48d2-b8ed-8ece35213705.png)

**Comment by Mereithhh** [comment]
感谢反馈，我处理一下

**Comment by Mereithhh** [comment]
这个问题是因为建站时间只精确到日期导致的，比如我今天 0902 号建站，但是因为没有具体的时间，会从今天的凌晨开始算。 我会在下个版本中加上详细的建站时分秒选项（可选且默认为此刻），您可以关注一下。

**Comment by Mereithhh** [comment]
已修复 `v0.28.1`
