### ISSUE TITLE
mongo用的是本地的还是公用的？

### ISSUE THREAD

**Issue by DingDangDog** [Mereithhh/van-blog#22]
大佬你好，不懂mongo和docker的小白一个，使用docker糊里糊涂搭建好了，请问使用的mongo是我服务器本地的还是你提供的？如何连接MongoDB查看我部署的服务所存储的数据？

**Comment by Mereithhh** [comment]
mongoDB 都是本地的，公用的我也付不起费用啊。 为了安全考虑默认的 `docker-compose.yml` 编排中的 `mongoDB` 是仅容器内访问的（换句话说不会对外保留端口）。

如果你想连接的话，首先需要修改编排中 `mongoDB` 的账密（对外暴漏端口有安全风险，一定要设置强密码！）：

![image](https://user-images.githubusercontent.com/22872368/188060179-e43978b0-9913-4f08-9af3-9fed66ff5675.png)

注意画红圈的地方要同步改，然后加上下图画红线的语句：

![image](https://user-images.githubusercontent.com/22872368/188060300-ac331409-7eec-4af4-b1db-e92922ddbaea.png)

然后运行 `docker-compose down && docker-compose up -d` 重启容器，就可以通过 `27017` 端口访问 `mongoDB` 了。

具体访问方式可以自行查阅资料，我一般都是用 [mongoDBCompass](https://www.mongodb.com/try/download/compass) 这个工具。

**Comment by Mereithhh** [comment]
我看了一下你的网站，头像图片好像没能正确显示。你可以检查一下是否添加 `oldmoon.top` 到 `VAN_BLOG_ALLOW_DOMAINS` 中了。

**Comment by DingDangDog** [comment]
好的，谢谢🤙
