### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by gt-tool** [Mereithhh/van-blog#24]
在按照文档部署之后，访问初始化页面(/admin/init)，Chrome浏览器会一直加载，并且在控制台报错

环境:
CentOS7.6

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/55085699/188254770-d07045a9-c208-4559-83ea-693a8ad26119.png">

**Comment by Mereithhh** [comment]
为了方便定位到问题，请您给我以下信息：

- 您用无痕窗口打开此页面，然后发给我一下网络请求的报错信息。

![image](https://user-images.githubusercontent.com/22872368/188255682-91ca31ab-55fb-40ec-9d68-ae622ef52d2d.png)

- 您检查一下是否设置了 `VAN_BLOG_CDN_URL` 这个环境变量，如果设置了，可以先注释掉启动再看看。
- 您把敏感信息注释掉，把用的 `docker-compose.yml` 文件内容发给我看看。
- 您用的是 ip 访问还是域名访问？

**Comment by Mereithhh** [comment]
或者您不建议的话，可以直接发给我地址，我自己看也行。。

**Comment by Mereithhh** [comment]
您用的是 `docker-compose` 的方式部署的吗

**Comment by gt-tool** [comment]
我历经了多次卸载重装，问题莫名消失了
目前已无法复现

说明：在无痕模式下或在其他浏览器network都无报错信息

**Comment by gt-tool** [comment]
是的

> 您用的是`docker-compose`什么方式部署的吗

**Comment by Mereithhh** [comment]
您可以排查一下浏览器插件，network 报错可能是浏览器插件导致的。（无痕模式默认不加载插件）

![image](https://user-images.githubusercontent.com/22872368/188257332-9d5804aa-c922-4830-ad4d-a0ff4a40727d.png)

**Comment by Mereithhh** [comment]
那这个 issue 我就先关闭了，有问题您再发起
