### ISSUE TITLE
系统在深色模式下，访问网站会闪过白色主题

### ISSUE THREAD

**Issue by gt-tool** [Mereithhh/van-blog#25]
当然...
有可能是我服务器带宽过低，加载过慢导致...

网址：gt-it.net

**Comment by Mereithhh** [comment]
## 原因
因为本质上这是静态网页，静态网页在生成时是根据服务器时间来的。 比如服务器是白天，所以首屏加载的静态页面一定是白色主题。 然后 js 加载中发现客户端系统是深色，然后切换到了深色主题。

## 可能的解决方案
您可以在后台设置首次访问的默认主题模式为黑色，可以让服务器首屏发来的静态页面就是黑色的。

![image](https://user-images.githubusercontent.com/22872368/188257456-0dc9ae5f-a2ee-4047-98c2-e24240e9d530.png)

## 后续
当然目前的主题切换逻辑也有一些值得完善的地方，我回头会排查一下，优化主题切换体验的。

## CDN
针对小带宽的情况，您可以通过 CDN 来提升加载速度。

[如何部署到 CDN](https://vanblog.mereith.com/ref/faq.html#%E5%A6%82%E4%BD%95%E9%83%A8%E7%BD%B2%E5%88%B0-cdn)

PS： CDN 加速理论上没得问题，但我没有详细测过，如遇到问题您可以再提 issue。（有空我会详细测一下 CDN 和不同带宽下的加载性能，放到项目文档给大家做参考的）

**Comment by Mereithhh** [comment]
这个 issue 就先关了哈。有问题再提
