### ISSUE TITLE
后台无法登录

### ISSUE THREAD

**Issue by hxcaihm** [Mereithhh/van-blog#26]
更新了版本（v0.30.0）之后，后台无法正常登录，报错`｛"statusCode":500,"message":"Internal server error"}`
![后台报错截图](https://user-images.githubusercontent.com/66231422/188268063-80954a82-df67-443e-94bd-c38b3e16a399.jpg)

Docker容器的日志报错`Cannot destructure property 'enableMaxLoginRetry' of '(intermediate value)' as it is null.`
![Docker容器报错](https://user-images.githubusercontent.com/66231422/188268127-f5fc034a-525a-4564-a90b-ae5e25e755fc.png)

**Comment by Mereithhh** [comment]
不好意思！我看一下，暂时您可以先回滚到上一个版本。

**Comment by Mereithhh** [comment]
不好意思！已经修复了，正在发版 `v0.30.1`，等出现更新提示后您更新一下应该就好了。

**Comment by hxcaihm** [comment]
好的，感谢！我待会更新试试

**Comment by Mereithhh** [comment]
不好意思，是我没考虑周到导致的。下次发布前我会尽量多做测试，避免这种情况的发生。

另外降级文档已经加上了。需要的话您可以参考一下 ：

![image](https://user-images.githubusercontent.com/22872368/188270403-238e9a89-e771-4381-85af-07d145cdce9c.png)

发版流水线比较慢，可能要大概1小时，暂时可以通过降级到 `v0.29.4` 来规避这个问题。

**Comment by hxcaihm** [comment]
感谢！更新版本v0.30.1后已可正常登录
