### ISSUE TITLE
32.0升级后Docker容器无限重启

### ISSUE THREAD

**Issue by gt-tool** [Mereithhh/van-blog#27]
升级方法：
<img width="712" alt="image" src="https://user-images.githubusercontent.com/55085699/188320112-c07e1931-0944-4979-b977-ec7e08928de3.png">

问题截图：
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/55085699/188319823-3586b0b3-79a4-4a97-a0b2-311f15c709fc.png">

**Comment by gt-tool** [comment]
后续：回滚至升级之前的版本就好了...

(我怎么一直遇见奇怪的问题)

**Comment by Mereithhh** [comment]
很抱歉给您造成困扰！您能提供一下容器内的报错日志不。但看这个我很难定位问题呀

**Comment by Mereithhh** [comment]
您之前的版本是多少呀

**Comment by Mereithhh** [comment]
更新：此问题是由于后台设置中的`网站 URL`格式错误导致的，实际上`网站 URL `需要填写包括协议的完整网址。

一会会紧急发一版修复这个问题，后台设置页面和初始化也会加上这个校验。

**Comment by Mereithhh** [comment]
已修复，正在发布的 `v0.32.1` 会处理 `网站 URL` 不正确的情况，后台也会在必要的地方验证并给出弹窗提示。
