### ISSUE TITLE
[问题反馈]: 页面前进后退行为异常

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#29]
### 问题描述 | Describe the bug

异常1：后退会把锚点带到上一页。
异常2：前进/后退有时不生效，像动图中的，我按了前进按钮，URL此时已经是`https://blog-demo.mereith.com/post/103#步骤`，但是页面还是首页的内容。

![动画](https://user-images.githubusercontent.com/14846416/188352184-247f9f37-9dbc-471f-8e2e-4941ca8c0791.gif)

### 复现网址 | Website URL

https://blog-demo.mereith.com/

### 版本 | Version

v0.32.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈！我处理一下

**Comment by Mereithhh** [comment]
### 进展

问题是因为用的目录组件年久失修加上和 `next.js` 内置的路由系统不太匹配导致的。

翻了一下目录组件的代码，发现比较混乱难以调试，决定自己实现目录组件了。

这需要一点时间，我会在下一版中解决这个问题。

**Comment by Mereithhh** [comment]
已修复 `v0.32.2`，替换成了自己实现的目录组件，自动增加锚点的功能先关了，后续研究一下怎么无副作用的加锚点再开启此功能。
