### ISSUE TITLE
小白提问

### ISSUE THREAD

**Issue by JobYu** [Mereithhh/van-blog#3]
怎么用阿里云虚拟主机搭建van-blog？

**Comment by Mereithhh** [comment]
不好意思，VanBlog 暂不支持虚拟主机部署。

虚拟主机提供的是网站托管服务，是针对特定场景的高度产品化服务，删减了很多应有的云服务器的权限和功能，也不支持运行 Docker。

`VanBlog` 除了网站展示本身，还包括了很多动态交互功能，比如后台、图床、评论等等。

从一开始 `VanBlog` 就是容器化设计的，没办法跑在不支持 Docker 的虚拟主机服务中。虽然可以独立部署，但由于内置了很多组件，会非常麻烦。

还是建议您使用云服务器或者轻量应用服务器部署 `VanBlog`，云服务器有更好的灵活性和可玩性，算下来其实更划算的。

小白向的教程已经在写了，写完会上到项目文档中。
