### ISSUE TITLE
[问题反馈]: 协作者权限异常及文章作者问题

### ISSUE THREAD

**Issue by hxcaihm** [Mereithhh/van-blog#31]
### 问题描述 | Describe the bug

1、协作者权限异常
协作者发布草稿权限异常，设置了草稿的所有权限，协作者依旧无法将草稿发布为文章。
2、协作者编写的文章，在文章页脚备注里，作者为网站作者，而不是编写作者。我想这个对于协作者来说是不公平的。

### 版本 | Version

v0.32.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈！我会尽快处理这个问题

**Comment by Mereithhh** [comment]
## 进展
协作者权限异常已经修复了，一会发版会上。

第二个问题，因为今天修的问题比较多，这个改动涉及的会比较广，我还没有广泛测试。所以明天再发版修复。

**Comment by Mereithhh** [comment]
协作者权限已修复，`v0.32.2`，第二个问题已处理但还没上线，明天测一下就上。这个 issue 就先关了哈。
