### ISSUE TITLE
[问题反馈]: 修改布局设置中时隐藏分类导航栏时提示网站 URL 不合法

### ISSUE THREAD

**Issue by heyi755** [Mereithhh/van-blog#32]
### 问题描述 | Describe the bug

修改布局设置中时隐藏分类导航栏时提示网站 URL 不合法，但没有url的输入呀

### 版本 | Version

v0.32.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，我看一下哈

**Comment by Mereithhh** [comment]
已经定位问题了，抱歉给您造成了影响，我一会发版会修好这个问题。等出现更新提示的时候您更新一下

**Comment by heyi755** [comment]
感谢开发者大大，这个博客网站真的完美符合我对博客的需求！祝越来越好！

**Comment by Mereithhh** [comment]
已经修复 `v0.32.2`，您更新一下就好了。

感谢支持！以后有什么意见或建议也欢迎提出哦~

此 issue 就先关啦。
