### ISSUE TITLE
[优化建议]: 文章历史版本

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#33]
### 功能概述 | Describe the feature

不知大佬有没有计划开发文章历史版本的功能，如果有该计划，我期望它有以下功能/特性：
- 该功能在管理后台实现
- 支持历史版本的预览
- 支持对比两个版本之间的差异
- 支持回滚到历史版本
- 修改文章时，支持给文章添加changelog

**Comment by Mereithhh** [comment]
感谢反馈！

之前是没有考虑过实现历史版本管理的，我会把您的需求记录下来放到排期中，未来会实现（暂时不会）。考虑如下：

- 实现历史版本功能实际上改动会比较大，会让系统复杂度上升，开发也比较久。（需要考虑导入导出等原有功能的影响，可能需要魔改编辑器甚至自己实现，需要考虑 diff 展示方案，等等） 
- 参考其他博客方案（hugo、halo、hexo 等）都并没有集成在后台的文章版本管理和文章级的 changelog。
- 比起历史版本，主题、拓展能力和插件生态的开发优先级更高一些。

一个相对好实现的方案是基于客户端（浏览器缓存）的历史版本，我可能会先实现这个方案。

您可以关注一下，说不定哪次升级之后就有了呢。

**Comment by Mereithhh** [comment]
此 issue 就先关了哈
