### ISSUE TITLE
[优化建议]: 自定义导航栏配置

### ISSUE THREAD

**Issue by starrySkyO** [Mereithhh/van-blog#34]
### 功能概述 | Describe the feature

目前的自定义导航只能新增，是否可以设置为全部自定义配置。并且可以配置多级导航。

**Comment by Mereithhh** [comment]
感谢反馈！这个需求很合理，我会加到 TODO 优先开发，您可以关注一下

**Comment by Mereithhh** [comment]
已填坑，下个版本会上，此 issue 就先关了哈
