### ISSUE TITLE
[优化建议]: 建议文章和草稿点击【保存】后能返回列表页，同时增加一个【返回】按钮，不保存返回

### ISSUE THREAD

**Issue by universeXiong** [Mereithhh/van-blog#35]

**Comment by Mereithhh** [comment]
感谢反馈！
- 我会在编辑器页面加一个保存按钮，点击后返回（目前来讲这和点击侧边栏的文章管理没有区别，但从其他地方进到编辑器可以返回到原来的路由）。
- 点击保存后的是留在编辑器页面还是跳转到列表，我个人还是喜欢留在编辑器页面的。所以我打算在保存确认弹窗时额外增加一个按钮。
- 这样保存确认就会有： 返回、保存、保存并返回，三个按钮。

您觉得这个方案怎么样？

**Comment by Mereithhh** [comment]
### 进展
我试了一下，保存确认三个按钮感觉很奇怪，还是两个按钮吧。 返回按钮加上确实不错

**Comment by Mereithhh** [comment]
至于保存按钮点击后的默认行为，我会做成一个配置项加到后台设置中

**Comment by Mereithhh** [comment]
![image](https://user-images.githubusercontent.com/22872368/188558508-d91a36e0-50b6-4885-af55-1121b7e72a5c.png)
![image](https://user-images.githubusercontent.com/22872368/188558530-344ad625-d657-4bde-ac8a-9d20b47ab7bf.png)

下个版本会上，这个 issue 就先关了哈

**Comment by universeXiong** [comment]
十分感谢！

**Comment by universeXiong** [comment]
很抱歉 昨天一直在开会  没能回复信息 真的很抱歉

**Comment by Mereithhh** [comment]
没关系，祝你用的开心，有问题随时反馈~
