### ISSUE TITLE
[优化建议]: 缩减镜像体积

### ISSUE THREAD

**Issue by chenrizhi** [Mereithhh/van-blog#36]
### 功能概述 | Describe the feature

我感觉镜像体积有点大，通过使用`dive`工具对镜像各层进行分析，发现有些缓存应该是可以被清理的。

![1662443077624](https://user-images.githubusercontent.com/14846416/188555955-72f70c00-9c6b-4e26-9a06-66d45039d584.jpg)

![1662443077637](https://user-images.githubusercontent.com/14846416/188555977-212c52d3-6fb4-4647-8b45-108332cc8c2a.jpg)

有几点优化的建议：
- 合并多个RUN，这两个RUN可以合并到一个RUN
  https://github.com/Mereithhh/van-blog/blob/987a8cbaf07366070b70807ab0599b7403bad127/Dockerfile#L53-L58
- 清除yarn缓存
  https://github.com/Mereithhh/van-blog/blob/987a8cbaf07366070b70807ab0599b7403bad127/Dockerfile#L63
  可以优化为：
  ```dockerfile
  RUN yarn && yarn cache clean
  ```
- 清除npm缓存
  https://github.com/Mereithhh/van-blog/blob/987a8cbaf07366070b70807ab0599b7403bad127/Dockerfile#L75
  可以优化为：
  ```dockerfile
  RUN cd  /app/website &&  npm install sharp && npm cache clean --force && cd ..
  ```

**Comment by Mereithhh** [comment]
感谢建议！我尝试一下！您有兴趣也欢迎提 PR

**Comment by Mereithhh** [comment]
试了一下，镜像体积小了不少，下一版将会应用这个改动，谢谢！
