### ISSUE TITLE
[优化建议]: markdown提示框

### ISSUE THREAD

**Issue by gt-tool** [Mereithhh/van-blog#37]
### 功能概述 | Describe the feature

大佬
markdown编辑器啥时候能支持带颜色的引用块作为提示框

![image](https://user-images.githubusercontent.com/55085699/188768605-f643da29-8c24-4a9d-aab8-5588810d4beb.png)

**Comment by Mereithhh** [comment]
你想要和项目文档这个一样的提示框语法吗？

**Comment by gt-tool** [comment]
> 你想要和项目文档这个一样的提示框语法吗？

是的


当然，也并不局限于这种样式，也可以是其他的样式，具体的话您这边来定就是了
![image](https://user-images.githubusercontent.com/55085699/188779729-27efc974-6960-4fb7-96c9-a2534e047547.png)

**Comment by Mereithhh** [comment]
好的，我安排一下。

**Comment by Mereithhh** [comment]
安排上了，下次升级更新

![image](https://user-images.githubusercontent.com/22872368/188861826-4f85eb0b-740b-4f32-9c8a-dd3857a632da.png)
