### ISSUE TITLE
[问题反馈]: 编辑文章无法放弃浏览器缓存

### ISSUE THREAD

**Issue by hxcaihm** [Mereithhh/van-blog#38]
### 问题描述 | Describe the bug

我已经修改了文章，而我再次点击编辑文章时，会读取缓存文章。此时我已经不需要这个缓存的文章了。但是我无法放弃他。
![缓存文章提示](https://user-images.githubusercontent.com/66231422/189037788-0734897b-5809-4965-8adc-5eab8f4c5da0.png)
如果这个缓存是保存在浏览器上。这个问题应该会在多端（或不同浏览器）编辑的情况下复现。
是否可以添加放弃机制，或者在恢复缓存后。主动点击返回按钮提示放弃缓存的文章呢？

### 版本 | Version

v0.36.0

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
您在操作下拉框中点击一下重置就好了。

**Comment by Mereithhh** [comment]
![image](https://user-images.githubusercontent.com/22872368/189039974-a79f3a91-df78-4b95-b921-ab89f86ef9c5.png)

**Comment by Mereithhh** [comment]
我做一个清空缓存的按钮吧。这样明显一点

**Comment by hxcaihm** [comment]
感谢！我不知道重置的作用是清除缓存，我一直以为他是清空编辑器的。

**Comment by Mereithhh** [comment]
不客气，也确实是我文案写的不清楚，下一版我加一个清空缓存的按钮，这样明显一点。祝您使用愉快
