### ISSUE TITLE
[问题反馈]: 友链添加超过5个以后无法继续添加

### ISSUE THREAD

**Issue by farewell12345** [Mereithhh/van-blog#39]
### 问题描述 | Describe the bug

友链添加超过5个以后无法继续添加，如图：
![image](https://user-images.githubusercontent.com/53655863/189159940-6d558f56-f345-4009-97ff-5297bc385c7f.png)
![image](https://user-images.githubusercontent.com/53655863/189160008-25a990f8-5a01-4c03-9d49-cf4a46adb6e1.png)

运行环境：
Ubuntu 20.04
Docker 20.10.5

### 复现网址 | Website URL

https://umb.ink/link

### 版本 | Version

v0.36.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈！我马上处理

**Comment by Mereithhh** [comment]
已修复，正在发版，等一会出现升级提示您升级一下就好了，很抱歉给您造成不便。

**Comment by Mereithhh** [comment]
已修复 `v0.36.2`
