### ISSUE TITLE
[优化建议]: 移动端的页面会产生左右晃动不固定问题

### ISSUE THREAD

**Issue by aarbbs** [Mereithhh/van-blog#40]
### 功能概述 | Describe the feature

如标题：移动端的页面会产生左右晃动不固定问题
平台：安卓
版本：安卓12
机型：红魔7s

**Comment by Mereithhh** [comment]
感谢反馈，您可以详细描述一下现象吗？我太懂左右晃动是啥意思… 
最好有个动图，谢谢！

**Comment by aarbbs** [comment]
描述：手指按住屏幕后，左右移动手指，观察整体页面是否存在晃动

见视频：[http://[begin2019.com:1234/van-blog-issue-40.mp4](http://begin2019.com:1234/van-blog-issue-40.mp4)](http://[begin2019.com:1234/van-blog-issue-40.mp4](http://begin2019.com:1234/van-blog-issue-40.mp4))

**Comment by Mereithhh** [comment]
您用的什么浏览器？ 我在我的手机上没能浮现这个问题😂

**Comment by aarbbs** [comment]
> 您用的什么浏览器？ 我在我的手机上没能浮现这个问题😂

edge浏览器

**Comment by Mereithhh** [comment]
好的

**Comment by Mereithhh** [comment]
## 进展

我分别在我的 `iphone 13 pro` 和 `小米 k40` 上用了 `chrome` 和 `edge` 浏览器，均未能复现这个问题。

为了可能的缩放原因，我发了一个 fix ，关闭了用户缩放。

此 issue 就先关了，如果您有能力可以在自己能复现的设备上修一下，欢迎 PR。
