### ISSUE TITLE
[优化建议]: 移动端点开菜单，双击菜单之外的区域时菜单会回弹

### ISSUE THREAD

**Issue by aarbbs** [Mereithhh/van-blog#41]
### 功能概述 | Describe the feature

复现步骤：
1. 点开导航菜单
2. 双击菜单外的空白区域

实际结果：
菜单缩回过程中又展开

预期结果：
菜单缩回不会展开

> 不知道是不是设计如此，由于测试过程中偶现左侧菜单意外弹出（或点击空白区域菜单关不掉），故提issue记录一下。

**Comment by Mereithhh** [comment]
## 进展
双击导航栏外侧遮罩区域会回弹，我看了一下是用的 `react-burger-menu` 这个组件的问题，但本身我认为这个设计没啥问题，为了这个设计特意去魔改这个组件或者给人家提个 issue/PR 不是很值。

`左侧菜单意外弹出`的问题，我之前也有遇到过，但最近重构了一些组件，今天再测试却并没有发现这个问题，可能是无意间被修复了。所以暂时先这样了，如果后续还有人遇到这个问题，我就直接拿掉 `react-burger-menu`，自己实现一个侧边抽屉组件了。

此 issue 就先关了哈
