### ISSUE TITLE
[问题反馈]: 草稿导入异常

### ISSUE THREAD

**Issue by universeXiong** [Mereithhh/van-blog#42]
### 问题描述 | Describe the bug

如图，我导入的草稿ID会有重复，之前有删除过重复的记录，现在导入ID一直都是4，删除会提示删除成功，但是数据不会有变动，也没有多删。
![草稿导入](https://user-images.githubusercontent.com/44185014/189467442-f8ffb968-ec97-4f54-ae4f-8be0eb588154.png)

### 版本 | Version

v0.36.2

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by universeXiong** [comment]
PS：ID数据库存储可以使用雪花id这种包含时间的格式，界面展示转成短ID展示，例如ea8R7k6这种。

**Comment by Mereithhh** [comment]
感谢反馈，我会尽快修复这个问题。 ID 之所以用数字是为了展示考虑，比如 `/post/12` 这种，在库中主键其实是 `MongoDB` 的 `ObjectID`，这个主键在前端是隐藏的。

**Comment by Mereithhh** [comment]
已修复，下个版本会更新。等出现更新提示您更新一下就好了（今天会发版）
PS： 之前修文章 ID 重复问题的时候忘了考虑草稿 ID 重复的问题了😂

现在已经存在的数据您方便的话进库删一下吧，或者手动给每个草稿改一个唯一 id（现在影响的人应该暂时不多，就不为了这个 bug 单独做一个特别清洗逻辑了）

**Comment by universeXiong** [comment]
OKK感谢
