### ISSUE TITLE
[优化建议]: 代码块颜色能否调整一下？

### ISSUE THREAD

**Issue by universeXiong** [Mereithhh/van-blog#43]
### 功能概述 | Describe the feature

如图，我在后台Markdown编辑器显示的效果：
![Markdown后台](https://user-images.githubusercontent.com/44185014/189467972-93b13c9c-0963-46ca-b6c5-d5177aa21306.png)
前台效果：
![Markdown前台](https://user-images.githubusercontent.com/44185014/189467990-41656b17-1caf-4e42-8c1f-c86bf0512061.png)

很明显后台看到的效果会舒服自然，而前台则是一屏幕白中突然黑一大块，显得很突兀。

**Comment by Mereithhh** [comment]
感谢反馈，这个坑我一直都想填的。

我会尽快填上的

**Comment by Mereithhh** [comment]
已填，前台代码块主题也会亮暗切换了，下次发版更新。但因为前后台用的 markdown 组件实现方式不同，所以代码块高亮主题有细微差别。（如果前台用和后台一样的亮色代码块主题，有些语法高亮不出来。改后台高亮主题的话需要自己写一个基于 prism.js 的高亮插件，暂时比较懒233）

![image](https://user-images.githubusercontent.com/22872368/189478215-40fd759b-be89-4e97-b2f2-98ccb6a620e0.png)
