### ISSUE TITLE
[问题反馈]: 后台修改密码

### ISSUE THREAD

**Issue by universeXiong** [Mereithhh/van-blog#45]
### 问题描述 | Describe the bug

应该是同 #44 一样的问题。
1、后台修改密码没有原始密码进行二次确认。
2、两个浏览器登录后台，一个浏览器修改密码后会被踢出登录，另一个还能正常刷新修改数据，甚至修改密码，导致之前修改的密码被覆盖。

### 版本 | Version

0.37.1

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈！
## 问题一
对于已经登录的超级用户来说，它已经具有权限了。

个人博客场景下，我不觉得二次确认密码有啥必要性，有时候只是忘了密码所以改一下，如果要二次确认但是忘了老密码，那岂不是改不了密码了？

个人博客场景下，只有一个超级用户（协作者除外），如果一个恶意者进入以超级用户进入后台，加不加修改密码二次确认，他都可以造成严重的后果。比如开启 https 自动重定向，比如删除数据，比如导出所有数据，导入覆盖所有现有数据等。相反即便他改了密码，也可以随时通过改库或者其他手段恢复。

## 问题二
同[上一个问题](https://github.com/Mereithhh/van-blog/issues/44)，JWT 的特性决定只要不更改部署时的 `VAN_BLOG_JWT_SECRET`，那签发有效期内的 Token 就一直生效，和版本升级没有关系，和修改密码也没关系。

但修改密码后老 Token 未强制过期是个问题，我会在后面增加修改密码后已签发的 Token 强制过期逻辑。

目前来讲，如果密码泄露了，可以在修改密码后同时修改部署时的 `VAN_BLOG_JWT_SECRET`，这样老的 Token 会强制过期。

## PS
我很喜欢 JWT 的无状态设计，但现实还是很骨感啊。到最后我还是要在服务器维护一套黑名单😂
>  [How to log out when using JWT](https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6)

**Comment by universeXiong** [comment]
对于问题一：正常情况下，敏感数据的操作，是需要二次验证的，譬如邮箱 | 短信等等，如果token泄露，那么这个恶意用户可以篡改所有数据，由于修改密码不需要二次确认，所有他可以通过修改密码以达到控制整个后台系统，虽说系统和数据都在我们手上，但这毕竟是个漏洞。
对于jwt：jwt的无状态确实很好，但它的确有一些不尽人意，我自己手头上的项目，是有对token进行管理的，包括创建、修改、过期时间，可以参考一下。
***
以上两点只是我稍微提一提，也犹豫了几天，毕竟这是一个个人博客系统，不是企业级项目，不可能天天有人搞你。

**Comment by Mereithhh** [comment]
我的意思是：他已经有 Token 了，即便加上了二次确认使他无法修改密码，但他也可以控制整个后台，没啥区别。如果 Token 泄露了，那其实底裤已经没了啊。

如果密码需要二次确认，那忘了老密码的用户将无法修改密码了（在不改库的前提下）。 所以我会在上线`忘记密码恢复功能`后再考虑增加修改密码需二次确认功能。

实际上修改敏感信息在某些场景是没有二次确认的，比如 `Github Actions 中的 Secret`，比如忘记密码重设的场景。
## 思考
### 接收邮箱验证码恢复密码
但问题是如果密码恢复功能是以`接收邮箱验证码`为前提的，那将会：
- 邮箱有被盗取的风险，可能会有钓鱼邮件攻击等。
- 改绑邮箱需不需要验证老邮箱？不需要的话，Token 泄露即便修改密码要二次确认，但攻击者可以通过改绑邮箱来绕过这个逻辑。 如果需要验证老邮箱，但老邮箱忘了密码咋办。
- 接收邮箱验证码的邮箱的 SMTP 要不要在后台配置，要的话 Token 泄露了，那邮箱也泄露了，攻击者也可以伪造此邮箱发送钓鱼邮件重设密码。
### 初始化随机生成恢复密钥恢复密码
如果采取初始化生成的恢复密钥恢复密码，那将会：
- 恢复密钥本身有泄露的风险
- 参考之前的，攻击者即便修改了密码，我也可以随时通过恢复密钥恢复密码。那泄露 Token 情况下，密码修改需不需要二次确认没有区别了。
### 后续
其实后续我打算精简部署时的环境变量，全部挪到后台进行配置的。此时如果 Token 泄露了，那造成的问题将更严重。

我个人觉得 Token 泄露就是底裤没了。所以我会增加一些 Token 管理和防泄漏的机制来尽可能保证安全。

问题二我会通过增加 Token 管理机制尽快修复，问题一我会在增加忘记密码重置功能后考虑处理。

您有什么想法欢迎随时交流，欢迎 PR~

**Comment by Mereithhh** [comment]
这个先关了呀。有问题随时找我，也可以加我 vx
