### ISSUE TITLE
[问题反馈]: 一进后台就提示登录失效

### ISSUE THREAD

**Issue by liesauer** [Mereithhh/van-blog#46]
### 问题描述 | Describe the bug

一进后台就提示登录失效
![image](https://user-images.githubusercontent.com/8676741/189795675-d3a98909-11e0-49a2-8a11-303b3b9ac6df.png)

### 复现网址 | Website URL

https://blog-demo.mereith.com/admin

### 版本 | Version

最新

### 部署方式？ | How do you deploy vanblog?

其他方式

**Comment by liesauer** [comment]
我从未登陆过后台，可以算是第一次进，所以理应不存在“旧的登陆凭证”，就不应该有这所谓的登录失效

**Comment by Mereithhh** [comment]
感谢反馈，之前偷懒只要后端给 401，前端就会提示登录失效。我修一下

**Comment by Mereithhh** [comment]
刚看了一下想起来了，这个问题我之前修了。之所以出现登录失效是因为前台管理员按钮点进去跳转的是 `/admin` ，这个路由下发现用户未登录，出现登录失效，然后再跳转到 `/admin/user/login`。  如果您直接在地址栏输入 `/admin/user/login` ,即便首次也不会出现登录失效的。

**Comment by Mereithhh** [comment]
已修复，下次发版上
