### ISSUE TITLE
[问题反馈]: 内置markdown编辑器不支持内联html语法吗

### ISSUE THREAD

**Issue by zzzqu** [Mereithhh/van-blog#47]
### 问题描述 | Describe the bug

图片居中，大小字体这些好像都不支持，有点难受，可以改进一下吗？

### 版本 | Version

最新

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
感谢反馈，前台实际上是支持内嵌 HTML 的，但后台编辑器确实暂不支持，我会尽快加上的。

暂时您可以正常编辑，虽然不能实时预览，但前台是可以出效果的

**Comment by Mereithhh** [comment]
已添加，一会发版上。
