### ISSUE TITLE
[优化建议]: 增加PicGo自定义插件安装功能

### ISSUE THREAD

**Issue by redgreat** [Mereithhh/van-blog#48]
## 后台新增加载插件功能

- 站点管理系统设置-图床设置 tab页，高级功能开放文本框安装插件名称
- 升级后还要保持插件能够重新加载（需要把插件列表放db里？）

不会写前端看引用，大佬帮做了吧
https://picgo.github.io/PicGo-Core-Doc/zh/api/#pluginhandler

**Comment by Mereithhh** [comment]
收到，回头研究一下

**Comment by Mereithhh** [comment]
安排上了。
![image](https://user-images.githubusercontent.com/22872368/191069103-40492ff0-4e05-4de3-801c-cce3b57c6895.png)

**Comment by Mereithhh** [comment]
下次发版会更新，到时候你试试呀。 你用的那个在后台写 `s3` 就好了。

![image](https://user-images.githubusercontent.com/22872368/191069695-224df45b-9fc2-438e-99a2-fc8fad4a1555.png)
