### ISSUE TITLE
[问题反馈]: 

### ISSUE THREAD

**Issue by furxt** [Mereithhh/van-blog#49]
### 问题描述 | Describe the bug

问题主要出现在日志功能上，进入页面就会出现`Failed to fetch`错误提示，具体可看您的demo演示，感觉是yaml配置文件少了日志相关的配置信息
![微信图片_20220915095432](https://user-images.githubusercontent.com/106371610/190294927-a67db589-55f3-46ea-b0ff-b79aa00f592c.jpg)

### 复现网址 | Website URL

https://blog-demo.mereith.com/admin/site/log

### 版本 | Version

latest

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
只是因为更新了版本，您清理一下浏览器缓存就好了（或者多刷新两次）
![image](https://user-images.githubusercontent.com/22872368/190299283-f7b63c6f-f09b-4daa-9aed-8dd85c0b7f70.png)

**Comment by Mereithhh** [comment]
为了给后台加速减少不必要的带宽消耗，默认开了缓存。但还不是很智能，更新版本有时候会这样，一般清理缓存或者多刷新几次就好了， 或者您开一个无痕窗口看看。

我后面会尝试把缓存搞智能一点的。

**Comment by Mereithhh** [comment]
## 补充
浏览器开了放广告插件可能也会导致这个问题。
