### ISSUE TITLE
求一个arm64版本的docker镜像😬

### ISSUE THREAD

**Issue by ZevaXu** [Mereithhh/van-blog#5]
用dockerfile不知道能不能编译成功，可以的话我自己编译一下

**Comment by Mereithhh** [comment]
理论上是没问题的，您可以先试一下。今天我会把 arm64 的加上

**Comment by Mereithhh** [comment]
已经加上了，现在新版镜像默认包含了 amd64 和 arm64 两种架构

![image](https://user-images.githubusercontent.com/22872368/187028051-be5f14d3-8132-4fa5-98c9-64d069bee1e5.png)

**Comment by ZevaXu** [comment]
OK,OK！居然已经运行成功！
![20220827-2336-h6VEzJ|450](https://cdn.jsdelivr.net/gh/ZevaXu/picupload@master/uPic/20220827-2336-h6VEzJ%7C450.png)
感谢！
