### ISSUE TITLE
[问题反馈]: 重新配置博客后，还是显示之前的页面

### ISSUE THREAD

**Issue by HalfwayHill** [Mereithhh/van-blog#50]
### 问题描述 | Describe the bug

我之前测试的时候，随便写了一个测试文章，但是当我正式使用(重新配置后)，无论怎么修改还是显示之前测试的页面，在后台也相应修改还是没有改变，我在重新配置前，已将caddy/data/log文件夹删除，增加文章也是只有一篇之前的测试文章，请问是否是没有删除缓存的问题，请问如何删除缓存？

### 复现网址 | Website URL

http://halflucky.cn

### 版本 | Version

最新版本

### 部署方式？ | How do you deploy vanblog?

Docker 部署(文档默认)

**Comment by Mereithhh** [comment]
看现象和缓存关系不大，一般而言前台不更新都是`反代或参数配置错误`导致的。

但我对您的问题没搞太明白，您可否提供以下信息：
- 您有没有切换浏览器/切换成隐私模式，或者换一个设备试试看是否前台会更新？
- 您是直接 docker 映射到了 80 端口，还是映射非常用端口自己反代的？如果是自己反代的，用的是啥反代软件，可否提供一下反代配置。
- 重新配置前，增加文章、修改文章是否前台会正常更新？
- 重新配置具体指什么，是删除了容器重启吗？这个过程中映射的本地目录有删除吗？有没有试试删除所有本地映射的目录，完全从头来过看看会不会出现这个问题？
- 重新配置后，新建文章前台是否会更新？
- 如果以上问题/尝试都无法解决此问题，可否提供一下您的 docker-compose 编排文件（关键信息请打码）和容器内的日志截图。 容器内日志可通过 `docker logs -f <容器名>` 获取。

谢谢，如果比较急切的话可以通过交流群私聊我，或者加我 vx。

**Comment by HalfwayHill** [comment]
你好
1. 我换了几个设备查看，前台没有更新
2. 我是直接使用的你的配置文件只是更改了网址
3. 重新配置前没有问题
4. 我重新停止了容器，并且删除了，我不知道映射的本地目录是哪个，我只是将vanblog目录下的文件删除其他，只剩yml文件，请问怎么删除本地映射目录
5. 重新配置后，新建文章前台不更新

**Comment by Mereithhh** [comment]
## 进展
刚才我们私聊了一下，这个问题是 CDN 缓存未更新导致的。

CDN 一般是用来加速静态资源访问速度的，VanBlog 前台更新后，CDN 不知道它更新了，还用的老数据就会出现这个问题。  
按照我的经验，有的 CDN 比较智能，会有跟随源站或者高级的配置项（比如设置一些缓存过期的规则之类的），可以比较快的刷新缓存（但也有一定的间隔时间，具体而言不一定）
我能想到的解决办法大概有三种：
1. 根据源站的缓存管理规则，设置一个好用的缓存策略，比如 vanblog 会通过 etag 之类的请求头控制缓存。 但我没有仔细研究过 CDN 缓存配置这方面，暂时也没有可以用的环境，如果有谁研究出来的话可以联系我，我把您的配置经验补充在文档中。（后面有时间的话我自己也会陆续补充一些配置教程）
2. 通过 API 强制刷新缓存，一般就是后台更新文章后，给 CDN 发送一个 API 来刷新缓存。但是目前 vanblog 的 hooks 功能还没开发完，后面 hooks 上线后就可以在特定事件后执行自定义的代码逻辑了。
3. 可以关了 CDN ，就没有问题了。
