### ISSUE TITLE
部署后，后台初始化一闪而过，登录页面显示 http error

### ISSUE THREAD

**Issue by XFRST** [Mereithhh/van-blog#6]
![image](https://user-images.githubusercontent.com/79140067/187066094-0187d389-c2b8-44a2-af6f-8bd14e845bea.png)

**Comment by Mereithhh** [comment]
您可以检查一下 `docker-compose` 编排文件，如果修改了下面的数据库账号密码，上面的也要同步修改。

**Comment by Mereithhh** [comment]
如果还是不能解决问题，请您把所用的 `docker-compose.yml` 文件给我看一下（敏感信息替换掉）

**Comment by Mereithhh** [comment]
![3ac04d638b3cc9fee7faefb89b835d7](https://user-images.githubusercontent.com/22872368/187068474-65559114-7d57-4b93-bd48-bbf8b0b119e5.jpg)

这两个地方的账号密码是对应的，实际上数据库是不会暴露到外面的（因为没有映射端口），所以默认账号密码不改也行。

改的要话要同步改。

比如您把下面的数据库账号密码改成了 `admin` 与`xxxx`。  

那对应的数据库链接地址也要改成: `mongodb://admin:xxxx@mongo:27017`

**Comment by XFRST** [comment]
非常感谢您的回复，问题解决了，原因是我把mongodb的端口映射出去了。
顺便问一下，为什么不能映射数据库呢，外部不能连接数据库吗？

**Comment by Mereithhh** [comment]
映射数据库是完全没问题的，默认没有映射端口是处于安全因素的考虑（怕有人设置一些弱口令）。

项目主页的编排中没有对外映射数据库却可以访问是基于这样的原理：

> 一个 docker-compose 内的容器可以通过 docker-compose.yml 中 services 下给定的名称互相访问。

如果想在外部访问数据库（映射端口），默认只需添加一行数据库映射指令，像下面这样：

![image](https://user-images.githubusercontent.com/22872368/187080577-163eadb4-8bc7-4f9c-af39-0b1951bba32d.png)

我测了一下这样是可以正常运行的。如果您映射端口后无法访问了，可以检查一下编排文件。可能是某些配置导致在 `vanblog` 的容器内无法通过`mongo:27017` 来访达另一个容器的 `27017` 端口。

或者您可以提供一下映射了端口却报错的编排文件，我帮您看看哪里有问题。

**Comment by XFRST** [comment]
映射问题解决了，可能是之前哪里写错了。
然后，作者logo无法加载，网站图标没有更新，用的本地图床，重启容器也没有加载。是对图片有什么要求吗？
![image](https://user-images.githubusercontent.com/79140067/187082000-e4017df3-7add-4e73-8368-0f579fa1c377.png)
![image](https://user-images.githubusercontent.com/79140067/187082031-a70f128c-b660-470b-ae50-6b30e19e6512.png)

**Comment by Mereithhh** [comment]
可能是您没设置 `VAN_BLOG_ALLOW_DOMAINS` 这个环境变量，比如您用的 `localhost` 访问，那需要设置 `VAN_BLOG_ALLOW_DOMAINS` 为 `localhost`，后续您确定了域名，比如时 `xxx.com` ，那可以一起写成 `localhost,xxx.com`

这是因为作者 logo 用了 `next.js` 的图片缓存技术，需要显式指明安全的域名。

网站图标不生效可能是之前的一个 bug 导致的，您可以参考文档中的升级指南，升级到最新版本，应该就修复了。

> [升级指南](https://vanblog.mereith.com/guide/update.html)

**Comment by Mereithhh** [comment]
![image](https://user-images.githubusercontent.com/22872368/187082427-8dcb83d2-ef39-4e55-981b-15d9ea286392.png)

**Comment by Mereithhh** [comment]
我先关闭了哈，有问题您再反馈。
