### ISSUE TITLE
git clone出现可以clone，不能check

### ISSUE THREAD

**Issue by darkchoco10099** [Mereithhh/van-blog#7]
'packages/admin/src/components/ImportArticleModal /index.jsx'，在该路径中由于/ImportArticleModal后有尾随空格，导致在clone代码的时候，提示可以clone，不能check，希望作者能完善一下使用体验，非常期待！

**Comment by Mereithhh** [comment]
不好意思，写的时候没注意到这一点。😂 现在正在重构前台 markdown 渲染器，发版的时候一起改过来。 等这一版稳定后，我会加上 commit 钩子检查一下代码风格的！

**Comment by Mereithhh** [comment]
您再试试，我把目录改过来了
