### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by yuanshanhshan** [Mereithhh/van-blog#8]
markdown 文件编辑，支持自动保存，防止编写内容丢失。

**Comment by Mereithhh** [comment]
草稿是有自动保存的。但文章还没有，下个版本会加上保存到浏览器缓存的功能。

**Comment by yuanshanhshan** [comment]
感谢回复，期待功能的更新。

**Comment by Mereithhh** [comment]
> 感谢回复，期待功能的更新。

新版已经加上了实时缓存功能，您可以升级试一下。（`v0.26.0`)
