### ISSUE TITLE
"url" parameter is not allowed

### ISSUE THREAD

**Issue by JiuMingZhu** [Mereithhh/van-blog#9]
作者大大您好,

`VAN_BLOG_ALLOW_DOMAINS` 设置为我自己的域名之后,作者头像依旧出现了 `400 Bad Request` 的错误

[测试url](http://andabao.top:8080/)

可能是镜像的错? [Reference](https://www.gyanblog.com/javascript/nextjs-fixing-load-external-images-url-parameter-not-allowed/#:~:text=Issue%3A-,Url%20Paramater%20Not%20Allowed,-If%20you%20are)

谢谢.

**Comment by JiuMingZhu** [comment]
我不小心吧https 重定向打开了,在研究怎么关闭中....

**Comment by Mereithhh** [comment]
emmmm ，我建议你删库或者换一个库。因为每次启动都会读取库中的反代配置并应用。

**Comment by Mereithhh** [comment]
最简单的办法是把 `docker-compose.yml` 文件中的 `VAN_BLOG_DATABASE_URL` 改为 `mongodb://vanBlog:vanBlog@mongo:27017/vanBlog1`，这样就换了一个库了。

**Comment by Mereithhh** [comment]
作者头像的问题你可以试试把端口号也加上看看。 比如你用的 8080 端口，就写 `xxxx.com:8080`

**Comment by Mereithhh** [comment]
关于 https 重定向，你也可以通过删除 `mongoDB` 库中 `settings` Collection 中的一项 `type=https`  的文档来恢复。

**Comment by Mereithhh** [comment]
镜像链接中的问题在很早之前就已经修复了，如果你加上端口号还是不行的话请加我微信 `cs3cx4g` ，我帮你好好看看。

**Comment by JiuMingZhu** [comment]
谢谢您耐心的回答,我刚接触docker 以及mongoDB. 需要时间自己研究一下,我先按照您的建议去自己折腾一下,现在得上班了Orz.
我先关了这个issue

**Comment by Mereithhh** [comment]
> 谢谢您耐心的回答,我刚接触docker 以及mongoDB. 需要时间自己研究一下,我先按照您的建议去自己折腾一下,现在得上班了Orz. 我先关了这个issue

ok，如果遇到不好解决的问题或者 bug 或者建议请联系我。

**Comment by JiuMingZhu** [comment]
谢谢,已经添加您微信了 有空请通过下~
